name: Bump Version

on:
  pull_request:
    types: [closed]

jobs:

  bump-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: conjikidow/bump-version@959c38cd5cf835c1f671a09a5202b7da8de76a0c # v2.0.3
        with:
          label-major: 'update::major'
          label-minor: 'update::minor'
          label-patch: 'update::patch'
          labels-to-add: 'automated,versioning'
          create-release: 'true'
